### PR TITLE
increase default timeout for client

### PR DESCRIPTION
**Pull request by ashhadsheikh**
Apple servers sometimes takes more than the default time causing client timeouts, increase the default timeout to cater increases response times.

https://github.com/awa/go-iap/issues/123

### CODE REVIEW

**Comment by takecy** [comment]
Sorry for the late confirmation.
Thanks for the pull request!
Looks good to me.

**Comment by OmarElGabry** [comment]
I think 10 seconds is not bad, if you are experiencing any issues, you can always override the default HTTP client with a reasonable timeout for your case. For us, we would assign a shorter timeout, and let it timeout, and retry the request rather than waiting > 10s.

```
NewWithClient(&http.Client{Timeout: 30 * time.Second})
```

cc: @takecy @ashhadsheikh 

That being said, can we revert this PR, please?.

**Comment by takecy** [comment]
You're right. I'll revert this PR.
Thanks for the appropriate advice.

**Comment by takecy** [comment]
@ashhadsheikh
This PR has been reverted.
If you want to change the default timeout value, 
please pass any HttpClient to the `NewWithClient` function to initialize it.

**Pull request merged**
