### PR TITLE
Added support for CONSUMPTION_REQUEST

### PR DESCRIPTION
**Pull request by leearmstrong**
Added support for CONSUMPTION_REQUEST

https://developer.apple.com/documentation/appstoreservernotifications/notification_type

### CODE REVIEW

**Review by takecy — APPROVED** [review]
Thanks for you pull request 😁 
It is OK that the CI is failing. I will fix it.

**Comment by takecy** [comment]
I released as 1.3.10. Please check it 😄 
https://github.com/awa/go-iap/releases/tag/1.3.10

**Comment by leearmstrong** [comment]
Thanks!

**Comment by leearmstrong** [comment]
I think the tag is wrong, is it `1.3.10` and should be `v1.3.10` ?

**Comment by takecy** [comment]
Oh Sorry,  I fixed it .
https://github.com/awa/go-iap/releases/tag/v1.3.10

**Pull request merged**
